In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__


'2.0.1+cu118'

### Introduction to tensors

##1. Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
print(scalar.ndim)
scalar.item()

0


7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [ ]:
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[0])

2
torch.Size([2, 2])
tensor([7, 8])


In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])
print(TENSOR[0][0])

3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])


###Random Tensors

Random tensors are imp becoz neural networks start with tensors full of random numbers and adjust them to better represent data

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8425, 0.1825, 0.2915, 0.8793],
        [0.8340, 0.9655, 0.7261, 0.1872],
        [0.5289, 0.1764, 0.9512, 0.2331]])

In [ ]:
print(random_tensor.ndim)
print(random_tensor.shape)


2
torch.Size([3, 4])


In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.ndim,random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

###Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

###Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

###Tensor Datatype

**Note**: 3 major errors run into with PyTorch
1. Tensors not right shape
2. Tensors not right datatype
3. Tenors not in right device

In [ ]:
tensor = torch.tensor([3,6,9],
                      dtype=None,
                      device=None,
                      requires_grad=False)
tensor

tensor([3, 6, 9])

### Manipulating Tensors
Tensor Operations:
*Addition
*Subtraction
*Multiplication(element-wise)
*Division
*Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10,torch.add(tensor,10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

###Matrix Multiplication

Two main ways of multiplication

1. Element-wise
2. Matrix multiplication(dot product)

In [ ]:
tensor*tensor

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
tensor_A.mm(tensor_B.T)  # mm is alias of matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# Finding the mean -> requires dtype to be float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
x.argmin(),x.argmax()

(tensor(0), tensor(9))

### Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping - reshapes an input tensor to a defined shape
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueeze - adds a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x.shape

torch.Size([9])

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z = x.view(3,3)
z,x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x = torch.zeros(1,1,4,4)
x,x.shape

(tensor([[[[0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.],
           [0., 0., 0., 0.]]]]),
 torch.Size([1, 1, 4, 4]))

In [ ]:
y = x.squeeze()
y,y.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([4, 4]))

In [ ]:
z = y.unsqueeze(dim=0)
z,z.shape

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([1, 4, 4]))

In [ ]:
w = z.permute(2,0,1)
w,w.shape

(tensor([[[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]]]),
 torch.Size([4, 1, 4]))

In [ ]:
w[1,0,0] = 1
z,w

(tensor([[[0., 1., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[0., 0., 0., 0.]],
 
         [[1., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.]]]))

### Pytorch tensors and numpy

Numpy is a popular scientific Python numerical computing library.

Pytorch has functionality to interact with it.

* Data in NumPy to PyTorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`


In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
array = array + 1
tensor #no change

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor,numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

### Reproducibility

#### Taking out random out of random

To reduce the randomness in neural networks and PyTorch comes the concept of *random seed*.

Random seed flavours the randomness

Resources:
* https://pytorch.org/docs/stable/notes/randomness.html


In [ ]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9641, 0.7464, 0.8325, 0.7326],
        [0.0970, 0.8171, 0.4113, 0.2904],
        [0.9751, 0.3637, 0.2823, 0.5630]])
tensor([[0.7606, 0.7702, 0.9045, 0.4319],
        [0.9489, 0.2690, 0.6927, 0.9020],
        [0.6084, 0.1093, 0.1100, 0.5275]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPU (and making computation faster)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA harware + PyTorch working together

Resource:
* https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
!nvidia-smi

Thu Jun  8 11:08:17 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of device
torch.cuda.device_count()

1

In [ ]:
#Putting tensor on GPU

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# Move tensor back to CPU

# If tensor on GPU can't transform it to numpy
tensor_back_on_CPU = tensor_on_GPU.cpu().numpy()
tensor_back_on_CPU

array([1, 2, 3])